export const SHOWLOGIN = 'SHOWLOGIN';
export const UPDATETOKEN = 'UPDATETOKEN';
export const UPDATENAVLIST = 'UPDATENAVLIST';
export const UPDATEUSERINFOR = 'UPDATEUSERINFOR';
export const UPDATEDEFAULTKEY = 'UPDATEDEFAULTKEY';
export const UPDATEACCESSTOKEN = 'UPDATEACCESSTOKEN';
export const UPDATEONLINESTATUS = 'UPDATEONLINESTATUS'
export const UPDATESEARCHINFO = 'UPDATESEARCHINFO';
