//礼物明细
{
    "code": 200,
    "message": "success",
    "data": {
        "lists_pages": 6,
        "lists": [{
            "uid": 9,
            "touid": 27,
            "giftid": 6,
            "giftcount": 1,
            "addtime": 1554090886,
            "giftname": "爱心",
            "nickname": "黄运",
            "tonickname": "zz"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 1,
            "addtime": 1549096762,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 1,
            "addtime": 1549096760,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 10,
            "addtime": 1549096757,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 10,
            "addtime": 1549096749,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 7,
            "giftcount": 10,
            "addtime": 1549096737,
            "giftname": "棒棒糖",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 8,
            "giftcount": 99,
            "addtime": 1549096723,
            "giftname": "麦克风",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 8,
            "giftcount": 99,
            "addtime": 1549096715,
            "giftname": "麦克风",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 99,
            "addtime": 1549096709,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 99,
            "addtime": 1549096707,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 10,
            "addtime": 1549096702,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 10,
            "addtime": 1549096700,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 10,
            "addtime": 1549096698,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 10,
            "addtime": 1549096696,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 19,
            "touid": 9,
            "giftid": 6,
            "giftcount": 10,
            "addtime": 1549096694,
            "giftname": "爱心",
            "nickname": "测试下",
            "tonickname": "黄运"
        }, {
            "uid": 12,
            "touid": 9,
            "giftid": 6,
            "giftcount": 1,
            "addtime": 1549002490,
            "giftname": "爱心",
            "nickname": "呵呵",
            "tonickname": "黄运"
        }, {
            "uid": 12,
            "touid": 9,
            "giftid": 9,
            "giftcount": 1,
            "addtime": 1549000041,
            "giftname": "饼干",
            "nickname": "呵呵",
            "tonickname": "黄运"
        }, {
            "uid": 12,
            "touid": 9,
            "giftid": 9,
            "giftcount": 1,
            "addtime": 1549000040,
            "giftname": "饼干",
            "nickname": "呵呵",
            "tonickname": "黄运"
        }, {
            "uid": 12,
            "touid": 9,
            "giftid": 9,
            "giftcount": 1,
            "addtime": 1549000040,
            "giftname": "饼干",
            "nickname": "呵呵",
            "tonickname": "黄运"
        }, {
            "uid": 12,
            "touid": 9,
            "giftid": 9,
            "giftcount": 1,
            "addtime": 1549000037,
            "giftname": "饼干",
            "nickname": "呵呵",
            "tonickname": "黄运"
        }]
    }
}
