var d = {
    "code": 200,
    "message": "success",
    "data": {
        "info": {
            "balance": "205649.66",
            "diamond": 5069
        },
        "list_pages": 2,
        "list": [{
            "id": 4,
            "user_id": 9,
            "money": 10,
            "diamond": 100,
            "type": 1,
            "stype": 3,
            "trade_no": "",
            "addtime": 1547460846,
            "reason": "0111",
            "type_name": "管理员充值"
        }, {
            "id": 18,
            "user_id": 9,
            "money": 98,
            "diamond": 980,
            "type": 1,
            "stype": 1,
            "trade_no": "2019012814233170833",
            "addtime": 1548656615,
            "reason": "",
            "type_name": "充值"
        }, {
            "id": 21,
            "user_id": 9,
            "money": 20000,
            "diamond": 200000,
            "type": 1,
            "stype": 3,
            "trade_no": "",
            "addtime": 1548658024,
            "reason": "测试",
            "type_name": "管理员充值"
        }, {
            "id": 22,
            "user_id": 9,
            "money": 1314,
            "diamond": 13140,
            "type": 1,
            "stype": 1,
            "trade_no": "2019012814482519293",
            "addtime": 1548658107,
            "reason": "",
            "type_name": "充值"
        }, {
            "id": 41,
            "user_id": 9,
            "money": 1314,
            "diamond": 13140,
            "type": 1,
            "stype": 1,
            "trade_no": "2019013013253253608",
            "addtime": 1548825934,
            "reason": "",
            "type_name": "充值"
        }, {
            "id": 5,
            "user_id": 9,
            "money": 10,
            "diamond": 100,
            "type": 2,
            "stype": 4,
            "trade_no": "",
            "addtime": 1547460913,
            "reason": "1111",
            "type_name": "管理员扣除"
        }, {
            "id": 19,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548656767,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 23,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548658324,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 24,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548658335,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 25,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548658340,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 26,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548658359,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 27,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548658368,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 28,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548658376,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 31,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548672892,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 32,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548672898,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 33,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548672902,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 34,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548672903,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 35,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548672908,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 36,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548672909,
            "reason": "",
            "type_name": "消费礼物"
        }, {
            "id": 37,
            "user_id": 9,
            "money": 0,
            "diamond": 888,
            "type": 2,
            "stype": 2,
            "trade_no": "",
            "addtime": 1548672915,
            "reason": "",
            "type_name": "消费礼物"
        }]
    }
}
