//省列表
var d = {
    "code": 200,
    "message": "success",
    "data": [{
        "linkageid": 2,
        "name": "北京市"
    }, {
        "linkageid": 3,
        "name": "上海市"
    }, {
        "linkageid": 4,
        "name": "天津市"
    }, {
        "linkageid": 5,
        "name": "重庆市"
    }, {
        "linkageid": 6,
        "name": "河北省"
    }, {
        "linkageid": 7,
        "name": "山西省"
    }, {
        "linkageid": 8,
        "name": "内蒙古"
    }, {
        "linkageid": 9,
        "name": "辽宁省"
    }, {
        "linkageid": 10,
        "name": "吉林省"
    }, {
        "linkageid": 11,
        "name": "黑龙江省"
    }, {
        "linkageid": 12,
        "name": "江苏省"
    }, {
        "linkageid": 13,
        "name": "浙江省"
    }, {
        "linkageid": 14,
        "name": "安徽省"
    }, {
        "linkageid": 15,
        "name": "福建省"
    }, {
        "linkageid": 16,
        "name": "江西省"
    }, {
        "linkageid": 17,
        "name": "山东省"
    }, {
        "linkageid": 18,
        "name": "河南省"
    }, {
        "linkageid": 19,
        "name": "湖北省"
    }, {
        "linkageid": 20,
        "name": "湖南省"
    }, {
        "linkageid": 21,
        "name": "广东省"
    }, {
        "linkageid": 22,
        "name": "广西"
    }, {
        "linkageid": 23,
        "name": "海南省"
    }, {
        "linkageid": 24,
        "name": "四川省"
    }, {
        "linkageid": 25,
        "name": "贵州省"
    }, {
        "linkageid": 26,
        "name": "云南省"
    }, {
        "linkageid": 27,
        "name": "西藏"
    }, {
        "linkageid": 28,
        "name": "陕西省"
    }, {
        "linkageid": 29,
        "name": "甘肃省"
    }, {
        "linkageid": 30,
        "name": "青海省"
    }, {
        "linkageid": 31,
        "name": "宁夏"
    }, {
        "linkageid": 32,
        "name": "新疆"
    }, {
        "linkageid": 33,
        "name": "台湾省"
    }, {
        "linkageid": 34,
        "name": "香港"
    }, {
        "linkageid": 35,
        "name": "澳门"
    }, {
        "linkageid": 3358,
        "name": "钓鱼岛"
    }]
}
//对应省的城市列表
var d1 = {
    "code": 200,
    "message": "success",
    "data": [{
        "linkageid": 295,
        "name": "武汉市"
    }, {
        "linkageid": 296,
        "name": "黄石市"
    }, {
        "linkageid": 297,
        "name": "十堰市"
    }, {
        "linkageid": 298,
        "name": "宜昌市"
    }, {
        "linkageid": 299,
        "name": "襄樊市"
    }, {
        "linkageid": 300,
        "name": "鄂州市"
    }, {
        "linkageid": 301,
        "name": "荆门市"
    }, {
        "linkageid": 302,
        "name": "孝感市"
    }, {
        "linkageid": 303,
        "name": "荆州市"
    }, {
        "linkageid": 304,
        "name": "黄冈市"
    }, {
        "linkageid": 305,
        "name": "咸宁市"
    }, {
        "linkageid": 306,
        "name": "随州市"
    }, {
        "linkageid": 307,
        "name": "恩施土家族苗族自治州"
    }, {
        "linkageid": 308,
        "name": "仙桃市"
    }, {
        "linkageid": 309,
        "name": "潜江市"
    }, {
        "linkageid": 310,
        "name": "天门市"
    }, {
        "linkageid": 311,
        "name": "神农架林区"
    }]
}
