 var d = {
     "code": 200,
     "message": "success",
     "data": {
         "auth_avatar": "https:\/\/pwgyy.gz.bcebos.com\/aa477801da1e4c189626d647d98d8949.png",
         "qq": "1111111111",
         "introduce": "111111111111",
         "title": "绝地求生",
         "logo": "http:\/\/img.pwg.com\/games\/jdqs_logo.png",
         "web_logo1": "http:\/\/img.pwg.com\/games\/jdqs_web_logo1.png",
         "web_logo2": "http:\/\/img.pwg.com\/games\/jdqs_web_logo2.png",
         "web_logo3": "http:\/\/img.pwg.com\/games\/jdqs_web_logo3.png",
         "screenshot": "http:\/\/img.pwg.com\/games\/jdqs.jpg",
         "lists": [{
             "title": "技能水平",
             "key": "jnsp",
             "lists": [{
                 "id": 1,
                 "value": "1000分",
                 "price": 15
             }, {
                 "id": 2,
                 "value": "1100分",
                 "price": 17
             }, {
                 "id": 3,
                 "value": "1200分",
                 "price": 18
             }, {
                 "id": 4,
                 "value": "1300分",
                 "price": 18
             }, {
                 "id": 5,
                 "value": "1400分",
                 "price": 19
             }, {
                 "id": 6,
                 "value": "1500分",
                 "price": 19
             }, {
                 "id": 7,
                 "value": "1600分",
                 "price": 20
             }, {
                 "id": 8,
                 "value": "1700分",
                 "price": 20
             }, {
                 "id": 9,
                 "value": "1800分",
                 "price": 21
             }, {
                 "id": 10,
                 "value": "1900分",
                 "price": 21
             }, {
                 "id": 11,
                 "value": "2000分",
                 "price": 25
             }, {
                 "id": 12,
                 "value": "2100分",
                 "price": 25
             }, {
                 "id": 13,
                 "value": "2200分",
                 "price": 26
             }, {
                 "id": 14,
                 "value": "2300分",
                 "price": 28
             }, {
                 "id": 15,
                 "value": "2400分",
                 "price": 30
             }, {
                 "id": 16,
                 "value": "2500分以上",
                 "price": 32
             }]
         }, {
             "title": "大区",
             "key": "daqu",
             "lists": [{
                 "id": 1,
                 "value": "Steam服"
             }, {
                 "id": 2,
                 "value": "国服"
             }]
         }, {
             "title": "擅长模式",
             "key": "scms",
             "lists": [{
                 "id": 1,
                 "value": "第三人称"
             }, {
                 "id": 2,
                 "value": "第一人称"
             }]
         }, {
             "title": "分类",
             "key": "fl",
             "lists": [{
                 "id": 1,
                 "value": "游戏辅导",
                 "beizhu": "辅助客户提升游戏技术、或提高客户的游戏体验。"
             }]
         }]
     }
 }
